import type { Service } from './types';

export const services: Service[] = [
  {
    id: '1',
    name: 'Anticuerpos Antinucleares (ANA)',
    description: 'Prueba de detección para autoanticuerpos que atacan el núcleo de las células. Esencial en el diagnóstico de enfermedades autoinmunes sistémicas.',
    methodology: 'Inmunofluorescencia Indirecta (IFI) en células HEp-2.',
    applications: 'Diagnóstico de Lupus Eritematoso Sistémico (LES), esclerodermia, síndrome de Sjögren, y otras enfermedades del tejido conectivo.',
    turnaroundTime: '5-7 días hábiles',
    category: 'Autoinmunidad',
  },
  {
    id: '2',
    name: 'Hemograma Completo',
    description: 'Análisis de sangre que mide la cantidad y calidad de glóbulos rojos, glóbulos blancos y plaquetas.',
    methodology: 'Citometría de Flujo.',
    applications: 'Detección de anemia, infecciones, leucemia y otros trastornos sanguíneos. Monitoreo de tratamientos.',
    turnaroundTime: '24 horas',
    category: 'Hematología',
  },
  {
    id: '3',
    name: 'Perfil de Alergia Respiratoria (IgE)',
    description: 'Mide los niveles de anticuerpos IgE específicos para un panel de alérgenos respiratorios comunes como pólenes, ácaros y epitelios de animales.',
    methodology: 'Inmunoensayo Quimioluminiscente (CLIA).',
    applications: 'Identificación de la causa de síntomas alérgicos como rinitis, asma y conjuntivitis.',
    turnaroundTime: '3-5 días hábiles',
    category: 'Alergias',
  },
  {
    id: '4',
    name: 'Cuantificación de Inmunoglobulinas (IgG, IgA, IgM)',
    description: 'Mide las concentraciones de las principales clases de inmunoglobulinas en la sangre para evaluar el estado del sistema inmune.',
    methodology: 'Nefelometría.',
    applications: 'Diagnóstico y monitoreo de inmunodeficiencias primarias y secundarias, gammapatías monoclonales e infecciones crónicas.',
    turnaroundTime: '2-3 días hábiles',
    category: 'Inmunodeficiencias',
  },
  {
    id: '5',
    name: 'Anticuerpos Anti-CCP (Péptido Cíclico Citrulinado)',
    description: 'Prueba altamente específica para el diagnóstico de Artritis Reumatoide.',
    methodology: 'ELISA (Ensayo por Inmunoabsorción Ligado a Enzimas).',
    applications: 'Diagnóstico temprano y pronóstico de la Artritis Reumatoide, diferenciándola de otras formas de artritis.',
    turnaroundTime: '4-6 días hábiles',
    category: 'Autoinmunidad',
  },
  {
    id: '6',
    name: 'Panel de Vasculitis (ANCA)',
    description: 'Detección de anticuerpos contra el citoplasma de neutrófilos (ANCA), asociados a vasculitis sistémicas.',
    methodology: 'IFI y ELISA.',
    applications: 'Diagnóstico de Granulomatosis con Poliangeítis (Wegener), Poliangeítis Microscópica y Síndrome de Churg-Strauss.',
    turnaroundTime: '7-10 días hábiles',
    category: 'Autoinmunidad',
  },
];
